version: '2.1'
services:
  # Сервис БД Postgresql
  db:
    image: postgres:11.6-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_date:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 3
    restart: always
  # Сервис для миграции БД Postgresql
  flyway:
    image: flyway/flyway
    container_name: migrate
    command: -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB} -schemas=public -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate 
    volumes:
      - ./migrate:/flyway/sql
    depends_on:
      db:
        condition: service_healthy